apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: tpc-gridftp
  namespace: osg-services
  labels:
    k8s-app: tpc-gridftp
spec:
  selector:
    matchLabels:
      k8s-app: tpc-gridftp
  template:
    metadata:
      labels:
        k8s-app: tpc-gridftp
    spec:
      tolerations:
      - effect: NoSchedule
        operator: Exists
      containers:
      - env:
        - name: OSG_FQDN
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: SITENAME
          value: TPC-GridFTP-PRPSite
        image: aaarora/gridftp-tpc:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9001
          hostPort: 9001
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "dd if=/dev/zero of=/mnt/ramdisk/testSourceFile bs=1G count=1"]       
        name: tpc-gridftp
        resources:
          limits:
            cpu: "6" 
            memory: 25Gi
#            ephemeral-storage: 40Gi
          requests:
            cpu: "4"
            memory: 20Gi
#            ephemeral-storage: 30Gi
        volumeMounts:
        - mountPath: /etc/gridftp.conf
          name: gridftp-tpc-conf
          subPath: gridftp.conf
        - mountPath: /mnt/ramdisk/
          name: cache-vol
        - mountPath: /etc/pki/CA/private/OSG-Test-CA.key
          name: ca
          subPath: OSG-Test-CA.pem
        - mountPath: /usr/lib/python2.7/site-packages/cagen.py
          name: cagen
          subPath: cagen.py
      dnsPolicy: ClusterFirst
      nodeSelector:
        nautilus.io/network: '100000'
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
      - name: ca
        secret:
          secretName: https-self-certs
          items:
          - key: OSG-Test-CA.pem
            path: OSG-Test-CA.pem
          defaultMode: 0644
      - name: cagen
        configMap: 
          name: cagen-script-modified
      - name: gridftp-tpc-conf
        configMap:
          name: gridftp-tpc-conf
      - name: cache-vol
        emptyDir:
          medium: Memory
          sizeLimit: 15Gi
